components:
  schemas:
    Auth:
      type: object
      properties:
        id:
          type: string
          description: The user ID.
        name:
          type: string
          description: The user's name.
      example:
        id: 123456789
        name: John Doe

